version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: labellecave
      POSTGRES_PASSWORD: labellecave
      POSTGRES_DB: labellecave
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user:
    depends_on:
      - postgres
    image: registry.robin-joseph.fr/labellecave-user:latest
    ports:
      - "8484:8484"

  product:
    depends_on:
      - postgres
    image: registry.robin-joseph.fr/labellecave-product:latest
    ports:
      - "8485:8485"

volumes:
  postgres_data:
