server:
  port: 8485

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/labellecave
    username: labellecave
    password: labellecave
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        jdbc:
          core: debug
    root: info

jwt:
  secret: yCEejd7w8gmc2LO4iv6vZYYW9yL2p1i3za9Fhm9ZdN2MmkFQ39t0RCWoOjC8TOnMNzH8fFVGKU6xffDYciRnAFTfakY8orzK6ShGlwJEnW4Ok9oHFUKx0XSTOrl14Ixa