name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all history
        run: git fetch --unshallow

      - name: Reset branch to remote
        run: git reset --hard origin/main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build user module
        run: mvn -f user/pom.xml clean package

      - name: SonarCloud analysis user module
        run: mvn -f user/pom.xml sonar:sonar -Dsonar.projectKey=robjo82_Labellecave -Dsonar.organization=robjo82 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
